### ISSUE TITLE
改成相对路径

### ISSUE THREAD

**Issue by Jerrypoi** [diesfd/GGPokerManager#1]
https://github.com/diesfd/GGPokerManager/blob/902fa6974c0c425165dca88194ceb08ef075acd6/RakeCounter.py#L8
要不要改成相对路径 QuQ

**Comment by diesfd** [comment]
> https://github.com/diesfd/GGPokerManager/blob/902fa6974c0c425165dca88194ceb08ef075acd6/RakeCounter.py#L8
> 
> 
> 要不要改成相对路径 QuQ

GG 遵命
